export const APP_CONFIG = {
  fileTemplates: {
    masterDataVendorsSheet: "Vendors",
    masterDataVendorsHeaders: [
      "name",
      "abbrName",
      "vendorNo",
      "contactPerson",
      "phoneNumber",
    ],
  },
  accountingSheets: {
    gl3311: "33110001",
    gl3312: "33120001",
  },
  supabase: {
    enabled: true,
    url: "https://cnqrljnducvsymquisfu.supabase.co",
    anonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucXJsam5kdWN2c3ltcXVpc2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NTUzNzAsImV4cCI6MjA4NzMzMTM3MH0.oxjM0UAUeq6BkY5yReYkh6-YiEG6G8mGHz7qpROm5so",
    schema: "public",
    channelName: "x3-realtime",
    storageMode: "envelope",
    tables: [
      "projects",
      "vendors",
      "contracts",
      "cpcItems",
      "installments",
      "bonds",
      "cpcDetailRows",
      "banks",
      "categories",
      "appState",
    ],
    tableNameMap: {
      projects: "projects",
      vendors: "vendors",
      contracts: "contracts",
      cpcItems: "cpcitems",
      installments: "installments",
      bonds: "bonds",
      cpcDetailRows: "cpcdetailrows",
      banks: "banks",
      categories: "categories",
      appState: "appstate",
    },
    primaryKeyMap: {
      appState: "key",
    },
  },
  auth: {
    enabled: true,
    provider: "google",
    tenantId: "YOUR_TENANT_ID",
    clientId: "YOUR_CLIENT_ID",
    authority: "",
    redirectUri: "",
    postLogoutRedirectUri: "",
    loginMode: "popup",
    scopes: ["openid", "profile", "email", "User.Read"],
    requiredRoles: ["x3.admin", "x3.editor", "x3.viewer"],
    roleClaimKeys: ["roles", "groups"],
    rolePermissions: {
      "x3.admin": ["*"],
      "x3.editor": [
        "dashboard.read",
        "data.read",
        "data.write",
        "import.execute",
        "export.execute",
        "masterdata.manage",
      ],
      "x3.viewer": ["dashboard.read", "data.read", "export.execute"],
    },
    defaultPermissions: ["dashboard.read", "data.read"],
    google: {
      clientId: "1065224246022-rq3ceb7vo4in6fui3e7g4romdurgr01o.apps.googleusercontent.com",
      hostedDomain: "",
      roleByDomain: {
        "your-company.com": "x3.editor",
      },
      roleByEmail: {
        "admin@your-company.com": "x3.admin",
        "ooanhduc@gmail.com": "x3.admin",
      },
    },
  },
};
